In [21]:
import torch
torch_scalar = torch.tensor(3.14)
torch_vector = torch.tensor([1, 2, 3, 4])
torch_matrix = torch.tensor([[1, 2,],
[3, 4,],
[5, 6,],
[7, 8,]])
torch_tensor3d = torch.tensor([
[
[ 1, 2, 3],
[ 4, 5, 6],
],
[
[ 7, 8, 9],
[10, 11, 12],
],
[
[13, 14, 15],
[16, 17, 18],
],
[
[19, 20, 21],
[22, 23, 24],
]
])

print(torch_scalar.shape)
print(torch_vector.shape)
print(torch_matrix.shape)
print(torch_tensor3d.shape)



torch.Size([])
torch.Size([4])
torch.Size([4, 2])
torch.Size([4, 2, 3])


In [22]:
import numpy as np
x_np = np.random.random((4,4))
print(x_np)


[[0.74889774 0.35724001 0.04058517 0.22815671]
 [0.67975881 0.52150334 0.54332185 0.62235681]
 [0.78902885 0.28739665 0.35375465 0.36063214]
 [0.24287506 0.00968419 0.98158    0.85784137]]


In [23]:
x_pt = torch.tensor(x_np)
print(x_pt)
print()
print(x_np.dtype, x_pt.dtype)


tensor([[0.7489, 0.3572, 0.0406, 0.2282],
        [0.6798, 0.5215, 0.5433, 0.6224],
        [0.7890, 0.2874, 0.3538, 0.3606],
        [0.2429, 0.0097, 0.9816, 0.8578]], dtype=torch.float64)

float64 torch.float64


In [37]:
x_np = np.asarray(x_np, dtype=np.float32)
x_pt = torch.tensor(x_np, dtype=torch.float32)
print(x_np.dtype, x_pt.dtype)


In [25]:
b_np = (x_np > 0.5)
print(b_np)
print(b_np.dtype)


[[ True False False False]
 [ True  True  True  True]
 [ True False False False]
 [False False  True  True]]
bool


In [26]:
b_pt = (x_pt > 0.5)
print(b_pt)
print(b_pt.dtype)


tensor([[ True, False, False, False],
        [ True,  True,  True,  True],
        [ True, False, False, False],
        [False, False,  True,  True]])
torch.bool


In [36]:
np.sum(x_np)


np.float32(7.6246133)

In [34]:
torch.sum(x_pt)

tensor(7.6246)

In [31]:
np.transpose(x_np)



array([[0.74889773, 0.6797588 , 0.7890288 , 0.24287505],
       [0.35724002, 0.5215033 , 0.28739664, 0.00968419],
       [0.04058517, 0.54332185, 0.35375464, 0.98158   ],
       [0.22815672, 0.62235683, 0.36063212, 0.8578414 ]], dtype=float32)

In [32]:
torch.transpose(x_pt, 0, 1)

tensor([[0.7489, 0.6798, 0.7890, 0.2429],
        [0.3572, 0.5215, 0.2874, 0.0097],
        [0.0406, 0.5433, 0.3538, 0.9816],
        [0.2282, 0.6224, 0.3606, 0.8578]])

In [38]:
print(torch.transpose(torch_tensor3d, 0, 2).shape)

torch.Size([3, 2, 4])
